name: build installers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - install/*

# Two separate jobs, first for multiarch (amd64, arm64), second for amd64 only

jobs:
  pushAmd:
    name: "debian-egg:install_amd:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - debian
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.7.0"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./install
          file: ./install/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/maxgestic/debian-egg:installer
